apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-list
  labels:
    app: shopping-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-list
  template:
    metadata:
      labels:
        app: shopping-list
    spec:
      containers:
      - name: shopping-list
        image: shopping-list:latest
        ports:
        - containerPort: 8080
        - containerPort: 8443
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["kill", "-SIGINT", "`pidof java`"]
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shopping-list
  name: shopping-list
spec:
  ports:
    - name: port-1
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: port-2
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: shopping-list
  sessionAffinity: None
  type: LoadBalancer

---
